START TRANSACTION;

ALTER TABLE "Entity" ADD "Ticker" character varying(20);

CREATE TABLE "EntityHierarchy" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedDate" timestamp NOT NULL,
    "ModifiedDate" timestamp,
    "CreatedBy" character varying(50) NOT NULL,
    "ModifiedBy" character varying(50),
    "Version" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsLatest" boolean NOT NULL,
    "EntityHierarchyInfo" text NOT NULL,
    "ClientId" integer NOT NULL,
    CONSTRAINT "PK_EntityHierarchy" PRIMARY KEY ("Id")
);

CREATE TABLE "SourceEntity" (
    "SourceId" character varying(20) NOT NULL,
    "Ticker" character varying(20) NOT NULL,
    "TickerAndExchCode" character varying(50) NOT NULL,
    "LongCompanyName" character varying(255) NOT NULL,
    "L1Industry" character varying(100),
    "L2Industry" character varying(100),
    "L3Industry" character varying(100),
    "L4Industry" character varying(100),
    "CompanyType" character varying(20),
    "CountryOfDomicile" character varying(20),
    "NoOfEmployees" integer,
    "CurrentMktCap" numeric(18,8),
    "PeRatio" numeric(18,8),
    "ParentTicker" character varying(20),
    "ParentLongName" character varying(255),
    "UltParentTicker" character varying(20),
    "UltParentName" character varying(255),
    "UltParentLongName" character varying(255),
    "GlobalCompanyName" character varying(255),
    "LeiName" character varying(255),
    "CompanyCorpTicker" character varying(20),
    "CompanyLegalName" character varying(255),
    "CompParentRelation" character varying(50),
    "LeiUltimateParent" character varying(255),
    "LatestFiling" character varying(20),
    CONSTRAINT "PK_SourceEntity" PRIMARY KEY ("SourceId"),
    CONSTRAINT "AK_SourceEntity_Ticker" UNIQUE ("Ticker")
);

CREATE TABLE "SourceFinancial" (
    "Ticker" character varying(20) NOT NULL,
    "EqyFundYear" integer NOT NULL,
    "FinCode" character varying(100) NOT NULL,
    "Currency" character varying(10),
    "Scaling" numeric,
    "FinValue" numeric,
    CONSTRAINT "PK_SourceFinancial" PRIMARY KEY ("Ticker", "EqyFundYear", "FinCode"),
    CONSTRAINT "FK_SourceFinancial_SourceEntity_Ticker" FOREIGN KEY ("Ticker") REFERENCES "SourceEntity" ("Ticker") ON DELETE CASCADE
);

CREATE TABLE "SourceRating" (
    "Ticker" character varying(20) NOT NULL,
    "BBRating" character varying(10),
    "BBRatingDate" timestamp with time zone,
    "BBRatingPrior" character varying(10),
    "MoodysRating" character varying(10),
    "MoodysRatingDate" timestamp with time zone,
    "MoodysOutlook" character varying(10),
    "MoodysOutlookDate" timestamp with time zone,
    CONSTRAINT "PK_SourceRating" PRIMARY KEY ("Ticker"),
    CONSTRAINT "FK_SourceRating_SourceEntity_Ticker" FOREIGN KEY ("Ticker") REFERENCES "SourceEntity" ("Ticker") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_SourceEntity_Ticker" ON "SourceEntity" ("Ticker");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241029081554_Release1', '8.0.5');

COMMIT;

